### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by Luyitas** [jiuntian/interactdiffusion#1]
Thanks for the impressive work reported in your paper, will the code be released soon?

**Comment by jiuntian** [comment]
Hi @Luyitas, thanks for your interest in our work, we are still working on releasing the code, please stay tune.

**Comment by jiuntian** [comment]
Hi @Luyitas, the code has been released. This issued will be closed.

**Comment by Luyitas** [comment]
Thanks for the code release!
