### ISSUE TITLE
dataset ask

### ISSUE THREAD

**Issue by ZhaoChenxi-nku** [jiuntian/interactdiffusion#10]
in HOI/interactdiffusion/dataset/hico_dataset.py

# Load tsv data
        self.files = glob.glob(os.path.join(self.dataset_path, 'embed_*.clip.pt'))
        assert len(self.files) > 0, f'No file found at {self.dataset_path}!'

what is the tsv data？

**Comment by jiuntian** [comment]
Please refer to 
https://github.com/jiuntian/interactdiffusion/tree/main/DATA#prepare-dataset
and
https://github.com/jiuntian/interactdiffusion?tab=readme-ov-file#training

**Comment by zhaochenxi515** [comment]
in https://github.com/jiuntian/interactdiffusion?tab=readme-ov-file#training HICO-DET dataset hico_det_clip.tar in OneDrive is empty

**Comment by zhaochenxi515** [comment]
Thank you!

**Comment by ZhaoChenxi-nku** [comment]
Thank you! 
Initially I opened OneDrive and found that its folder was empty, and just found out that I could download hico_det_clip dataset just by click it.
I'll try again after downloading the dataset.
