### ISSUE TITLE
Diffusers codes: ModuleNotFoundError: No module named 'interactdiffusion_unet_2d_condition'

### ISSUE THREAD

**Issue by Kenneth-Wong** [jiuntian/interactdiffusion#3]
When I run the diffuser code : No module named 'interactdiffusion_unet_2d_condition'.

Are sth. missed?

**Comment by jiuntian** [comment]
Please check the colab notebook for the usage:
https://colab.research.google.com/drive/1Bh9PjfTylxI2rbME5mQJtFqNTGvaghJq?usp=sharing
I have just re-ran the code and it is working correctly.

The diffusers code: https://huggingface.co/interactdiffusion/diffusers-v1-2

If you wish to clone to local and perform changes to the code, you may initialise the pipeline as the following:
```python
pipeline = DiffusionPipeline.from_pretrained(
    "<local path to cloned interactdiffusion diffusers code>",
    variant="fp16", torch_dtype=torch.float16
)
```

The `interactdiffusion_unet_2d_condition.py` is in unet folder.

Feel free to leave the comment if the problem persists.
