### ISSUE TITLE
Please Release clip_phrases_feature_cache.pth

### ISSUE THREAD

**Issue by EchoForger** [jiuntian/interactdiffusion#5]
Could not find file `clip_phrases_feature_cache.pth`

The time for inference using the code is too long. Could you please directly upload this file to the community? Thank you.

**Comment by jiuntian** [comment]
[clip_phrases_feature_cache.pth.zip](https://github.com/jiuntian/interactdiffusion/files/14978141/clip_phrases_feature_cache.pth.zip)

Please try with this file. However, it only helps in reducing CLIP inference time, which is not very significant. Hope this helps. Feel free to reopen this issue if any problems.
