### ISSUE TITLE
hico_det_clip

### ISSUE THREAD

**Issue by BlackPuuuudding** [jiuntian/interactdiffusion#6]
Is the embedding of the hico_det_clip dataset obtained through InBedding as described in the paper?

**Comment by jiuntian** [comment]
No. For InBedding, please refer to [text_grounding_net.py](https://github.com/jiuntian/interactdiffusion/blob/main/ldm/modules/diffusionmodules/text_grounding_net.py ).

**Comment by Hayeon-kimm** [comment]
Then, what is hico_det_clip? As I know, it is from the GLIGEN(ckpt). But, original GLIGEN couldn't give the HICO-DET tsv. So can you share with us?

**Comment by jiuntian** [comment]
Check here https://github.com/jiuntian/interactdiffusion/blob/main/DATA/readme.md
