### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by Hammour-steak** [jiuntian/interactdiffusion#8]
When I use the command `python inference_batch.py --batch_size 1 --folder generated_output --seed 489 --scheduled-sampling 1.0 --half`, unexpected error occurs: 
```
RuntimeError: Error(s) in loading state_dict for FrozenCLIPEmbedder:
        Unexpected key(s) in state_dict: "transformer.text_model.embeddings.position_ids".
```
It origins from the code: `text_encoder = instantiate_from_config(config['text_encoder']).to(device).eval()` in `inference.py`,
Incidentally, I used `interact-diffusion-v1.pth`. Is there anything wrong in this checkpoint? Thank you.

**Comment by jiuntian** [comment]
New version of `transformers` library used a different name for `transformer.text_model.embeddings.position_ids`. Using an older version, `pip install transformers==4.30.1` works for me.

**Comment by Hammour-steak** [comment]
Thank you, it works now.

**Comment by Hammour-steak** [comment]
![112](https://github.com/jiuntian/interactdiffusion/assets/51786922/7700f10b-13ec-4d60-a8c2-9e5a8542c25e)
It seems that a little difference from what the paper reports when I used the pretrained model v1.0

**Comment by jiuntian** [comment]
It could be attributed to randomness in random initial noises.
